{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.1.jar",
          "url": "spring-oxm-6.1.1.jar",
          "size": 59804,
          "sha512": "9d63c72477c762213cafcffa1bd3123893507402010bacf462093a3d756a4f1c79b2685a031cca7ecad97e2d352fa51a1d97c65e3a5ec7c98050bcb026a5da09",
          "sha256": "66c4ca2ae655570977023536206a0f98e9fdaf057a0f2bc444b7849816efdbe6",
          "sha1": "2940702b9f9d4396abb9abe28229eda49edf54fe",
          "md5": "cf2da66296dc10379877e76b7d270c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.1.jar",
          "url": "spring-oxm-6.1.1.jar",
          "size": 59804,
          "sha512": "9d63c72477c762213cafcffa1bd3123893507402010bacf462093a3d756a4f1c79b2685a031cca7ecad97e2d352fa51a1d97c65e3a5ec7c98050bcb026a5da09",
          "sha256": "66c4ca2ae655570977023536206a0f98e9fdaf057a0f2bc444b7849816efdbe6",
          "sha1": "2940702b9f9d4396abb9abe28229eda49edf54fe",
          "md5": "cf2da66296dc10379877e76b7d270c28"
        }
      ]
    }
  ]
}
