{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor.addons",
    "module": "reactor-extra",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-extra-3.5.1.jar",
          "url": "reactor-extra-3.5.1.jar",
          "size": 104458,
          "sha512": "24527d675805e636e06624e99b47d8939254c5e15b2ccf8531996f6ced08d3905b0c110dbe3ded8530efcec404925fb26c79efda82a7b18c9b0dd88f10a28893",
          "sha256": "523e4ff3e80bb9c15702bbb4e3912462dca4a9888c88fc3ddfe560f3783756e2",
          "sha1": "227cd47421ca0571c662f67428903c5c54777ef1",
          "md5": "14e0470afd09e039ead03cbb9da28a72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-extra-3.5.1.jar",
          "url": "reactor-extra-3.5.1.jar",
          "size": 104458,
          "sha512": "24527d675805e636e06624e99b47d8939254c5e15b2ccf8531996f6ced08d3905b0c110dbe3ded8530efcec404925fb26c79efda82a7b18c9b0dd88f10a28893",
          "sha256": "523e4ff3e80bb9c15702bbb4e3912462dca4a9888c88fc3ddfe560f3783756e2",
          "sha1": "227cd47421ca0571c662f67428903c5c54777ef1",
          "md5": "14e0470afd09e039ead03cbb9da28a72"
        }
      ]
    }
  ]
}
