name: 'Setup Docker'
description: 'Common Docker setup steps: buildx and registry login'

inputs:
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  platforms:
    description: 'Docker buildx platforms (comma-separated)'
    required: false
    default: 'linux/amd64'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}