{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netflix.eureka",
    "module": "eureka-client",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.netflix.netflix-commons",
          "module": "netflix-eventbus",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.netflix.archaius",
          "module": "archaius-core",
          "version": {
            "requires": "0.7.6"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.netflix.servo",
          "module": "servo-core",
          "version": {
            "requires": "0.12.21"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.vlsi.compactmap",
          "module": "compactmap",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5.1"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "eureka-client-2.0.1.jar",
          "url": "eureka-client-2.0.1.jar",
          "size": 404249,
          "sha512": "792a2f72e46c16c43109819167b2e2d53ccd51bf9433a08ae9017c117685000efce49eed3d37847ce55c72114769b10ba9d756f5b9c03d16b07da71609ac6f17",
          "sha256": "b566ce876648859df6c09059d865c9ad4e670ef1f098480f2163f3b692f0ed72",
          "sha1": "4f81f1bc22afc1390febbda4a711b35dd4327e68",
          "md5": "400e7df251465855d183bfb1cb44552d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netflix.netflix-commons",
          "module": "netflix-eventbus",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.netflix.archaius",
          "module": "archaius-core",
          "version": {
            "requires": "0.7.6"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.netflix.servo",
          "module": "servo-core",
          "version": {
            "requires": "0.12.21"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.vlsi.compactmap",
          "module": "compactmap",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5.1"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jettison",
          "module": "jettison",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.glassfish.jersey",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "eureka-client-2.0.1.jar",
          "url": "eureka-client-2.0.1.jar",
          "size": 404249,
          "sha512": "792a2f72e46c16c43109819167b2e2d53ccd51bf9433a08ae9017c117685000efce49eed3d37847ce55c72114769b10ba9d756f5b9c03d16b07da71609ac6f17",
          "sha256": "b566ce876648859df6c09059d865c9ad4e670ef1f098480f2163f3b692f0ed72",
          "sha1": "4f81f1bc22afc1390febbda4a711b35dd4327e68",
          "md5": "400e7df251465855d183bfb1cb44552d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eureka-client-2.0.1-javadoc.jar",
          "url": "eureka-client-2.0.1-javadoc.jar",
          "size": 1107816,
          "sha512": "825c7b908cccb17eb2df9025fbeb1743d870ee5358aec89ecd231579bac069526ebd610cbaa3df324336b72d5231dc7b8b9085d966e21a8ec00b2e69694e677b",
          "sha256": "71838d7ca95840902dfb331b854363485880b593e3d8a62a5c738d67670f7783",
          "sha1": "3c57d76f669643cf10016d62f99d970c6b1baaa3",
          "md5": "aee9ce9997273a48dd0bd81ae383007b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eureka-client-2.0.1-sources.jar",
          "url": "eureka-client-2.0.1-sources.jar",
          "size": 233697,
          "sha512": "b610e31108357bc997816dd95a7c9feaf8db9628f40ed695d03f643c25959fb8aecd842f0cea868a942d65c53052f9eaeb130e4b6d2b00ccf767788fe6020655",
          "sha256": "d23165e7f33c284e1b693fc82aa64c4266d71cc6799614900ba1b9f76bfc6045",
          "sha1": "041312433e41300c85a234249ff1b4edb0e113a0",
          "md5": "99663b8f71795a8c41881aa112dc782b"
        }
      ]
    }
  ]
}
