{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.1.jar",
          "url": "spring-context-support-6.1.1.jar",
          "size": 174054,
          "sha512": "05e307d9b0c88883122e3ecc328566230fb1db1950f2110d2ea87cff7cb9138fe0771577d3b21ad36215ff60df0b734bd488ac95c182b5d0f32740558327d536",
          "sha256": "f90ae45bf493a545d9cbec84c6c31708e4c6cf51357e4a819f87bcb50260cab7",
          "sha1": "b24f79e495719e0a47affab13724bf7a6e1d8941",
          "md5": "08191926a4ec623388b879edfa1c70c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.1.jar",
          "url": "spring-context-support-6.1.1.jar",
          "size": 174054,
          "sha512": "05e307d9b0c88883122e3ecc328566230fb1db1950f2110d2ea87cff7cb9138fe0771577d3b21ad36215ff60df0b734bd488ac95c182b5d0f32740558327d536",
          "sha256": "f90ae45bf493a545d9cbec84c6c31708e4c6cf51357e4a819f87bcb50260cab7",
          "sha1": "b24f79e495719e0a47affab13724bf7a6e1d8941",
          "md5": "08191926a4ec623388b879edfa1c70c5"
        }
      ]
    }
  ]
}
